const fs = require('fs');
let code = fs.readFileSync('lib/brands.ts', 'utf8');

const domains = {
  "walmart": "walmart.com",
  "uber": "uber.com",
  "target": "target.com",
  "mcdonalds": "mcdonalds.com",
  "starbucks": "starbucks.com",
  "burger-king": "bk.com",
  "wendy-s": "wendys.com",
  "subway": "subway.com",
  "taco-bell": "tacobell.com",
  "kfc": "kfc.com",
  "chipotle": "chipotle.com",
  "domino-s-pizza": "dominos.com",
  "pizza-hut": "pizzahut.com",
  "papa-john-s": "papajohns.com",
  "chick-fil-a": "chick-fil-a.com",
  "panera-bread": "panerabread.com",
  "five-guys": "fiveguys.com",
  "in-n-out-burger": "in-n-out.com",
  "shake-shack": "shakeshack.com",
  "panda-express": "pandaexpress.com",
  "sonic-drive-in": "sonicdrivein.com",
  "dairy-queen": "dairyqueen.com",
  "arby-s": "arbys.com",
  "jack-in-the-box": "jackinthebox.com",
  "popeyes": "popeyes.com",
  "dunkin": "dunkinbrands.com",
  "tim-hortons": "timhortons.com",
  "peet-s-coffee": "peets.com",
  "caribou-coffee": "cariboucoffee.com",
  "dutch-bros": "dutchbros.com",
  "jamba-juice": "jamba.com",
  "boba-guys": "bobaguys.com",
  "costco": "costco.com",
  "sam-s-club": "samsclub.com",
  "whole-foods": "wholefoodsmarket.com",
  "trader-joe-s": "traderjoes.com",
  "kroger": "kroger.com",
  "publix": "publix.com",
  "safeway": "safeway.com",
  "aldi": "aldi.us",
  "walgreens": "walgreens.com",
  "cvs-pharmacy": "cvs.com",
  "home-depot": "homedepot.com",
  "lowe-s": "lowes.com",
  "ikea": "ikea.com",
  "best-buy": "bestbuy.com",
  "macy-s": "macys.com",
  "nordstrom": "nordstrom.com",
  "sephora": "sephora.com",
  "ulta-beauty": "ulta.com",
  "gamestop": "gamestop.com",
  "apple-store": "apple.com",
  "tj-maxx": "tjmaxx.tjx.com",
  "marshalls": "marshalls.com",
  "dick-s-sporting-goods": "dickssportinggoods.com",
  "petco": "petco.com",
  "petsmart": "petsmart.com",
  "autozone": "autozone.com",
  "o-reilly-auto-parts": "oreillyauto.com",
  "amazon": "amazon.com",
  "ebay": "ebay.com",
  "netflix": "netflix.com",
  "spotify": "spotify.com",
  "hulu": "hulu.com",
  "disney": "disneyplus.com",
  "apple-services": "apple.com",
  "google-play": "play.google.com",
  "microsoft-store": "microsoft.com",
  "steam": "store.steampowered.com",
  "playstation-store": "playstation.com",
  "xbox-store": "xbox.com",
  "adobe": "adobe.com",
  "zoom": "zoom.us",
  "lyft": "lyft.com",
  "doordash": "doordash.com",
  "uber-eats": "ubereats.com",
  "grubhub": "grubhub.com",
  "postmates": "postmates.com",
  "instacart": "instacart.com",
  "airbnb": "airbnb.com",
  "expedia": "expedia.com",
  "booking-com": "booking.com",
  "delta-airlines": "delta.com",
  "american-airlines": "aa.com",
  "united-airlines": "united.com",
  "southwest-airlines": "southwest.com",
  "marriott": "marriott.com",
  "hilton": "hilton.com",
  "hyatt": "hyatt.com",
  "hertz": "hertz.com",
  "enterprise": "enterprise.com",
  "avis": "avis.com",
  "7-eleven": "7-eleven.com",
  "shell": "shell.com",
  "chevron": "chevron.com",
  "exxon": "exxon.com",
  "mobil": "mobil.com",
  "bp": "bp.com",
  "speedway": "speedway.com",
  "wawa": "wawa.com",
  "quiktrip": "quiktrip.com",
  "sheetz": "sheetz.com",
  "barnes-noble": "barnesandnoble.com",
  "michaels": "michaels.com",
  "joann": "joann.com",
  "zara": "zara.com",
  "h-m": "hm.com"
};

for (const [slug, domain] of Object.entries(domains)) {
  const searchStr = `slug: "${slug}",`;
  const logoUrl = `https://logo.clearbit.com/${domain}`;
  
  // Find the defaults block for this slug
  const slugIndex = code.indexOf(searchStr);
  if (slugIndex === -1) continue;
  
  const defaultsIndex = code.indexOf('defaults: {', slugIndex);
  if (defaultsIndex === -1) continue;
  
  const insertIndex = defaultsIndex + 'defaults: {'.length;
  code = code.slice(0, insertIndex) + `\n      logoDataUrl: "${logoUrl}",` + code.slice(insertIndex);
}

fs.writeFileSync('lib/brands.ts', code);
console.log('Logos added');
