// One-time build helper: resolve each brand's official logo from Wikimedia.
//
// Strategy: search Wikidata for the brand, then pick the entity whose
// "official website" (P856) matches the brand's domain — this disambiguates
// e.g. "Apple Inc." from the fruit. We read the "logo image" (P154) of that
// entity and resolve it to a stable upload.wikimedia.org thumbnail URL
// (which serves Access-Control-Allow-Origin: *, so it embeds into exports).
//
// Output: lib/brand-logos.ts (a domain -> logo URL map). Misses are omitted
// and fall back to the favicon proxy at runtime.
//
// Run with: node scripts/resolve-logos.mjs

import { readFile, writeFile } from "node:fs/promises";

const UA = "MakecepeitLogoResolver/1.0 (https://makecepeit.com; hello@makecepeit.com)";
const WIDTH = 320;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function j(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA, Accept: "application/json" } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

function registrable(host) {
  return host.replace(/^www\./, "").toLowerCase();
}

async function resolveLogoFile(name, domain) {
  const search = await j(
    `https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&language=en&type=item&limit=7&search=${encodeURIComponent(
      name
    )}`
  );
  const ids = (search.search ?? []).map((s) => s.id);
  if (ids.length === 0) return null;

  const ent = await j(
    `https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&props=claims&ids=${ids.join("|")}`
  );

  const target = registrable(domain);

  // Only trust an entity whose official website (P856) matches the brand's
  // domain. This avoids wrong matches like Wawa -> Warsaw. No match => null,
  // which falls back to the favicon proxy (reliable, just less fancy).
  for (const id of ids) {
    const claims = ent.entities?.[id]?.claims ?? {};
    const logo = claims.P154?.[0]?.mainsnak?.datavalue?.value;
    if (!logo) continue;

    const sites = (claims.P856 ?? [])
      .map((c) => c.mainsnak?.datavalue?.value)
      .filter(Boolean);
    for (const site of sites) {
      try {
        const host = registrable(new URL(site).hostname);
        if (host === target || host.endsWith(`.${target}`) || target.endsWith(`.${host}`)) {
          return logo;
        }
      } catch {
        /* ignore malformed urls */
      }
    }
  }

  return null;
}

async function finalThumbUrl(fileName) {
  const url = `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(
    fileName
  )}?width=${WIDTH}`;
  const res = await fetch(url, { headers: { "User-Agent": UA }, redirect: "follow" });
  if (!res.ok) return null;
  return res.url; // resolved upload.wikimedia.org thumbnail
}

async function main() {
  const src = await readFile(new URL("../lib/brands.ts", import.meta.url), "utf8");

  // Extract (shortName, domain) per brand in file order.
  const shortNames = [...src.matchAll(/shortName:\s*"([^"]+)"/g)].map((m) => m[1]);
  const domains = [...src.matchAll(/brandLogo\("([^"]+)"\)/g)].map((m) => m[1]);
  if (shortNames.length !== domains.length) {
    throw new Error(`mismatch: ${shortNames.length} names vs ${domains.length} domains`);
  }
  const brands = domains.map((domain, i) => ({ domain, name: shortNames[i] }));
  console.error(`Resolving ${brands.length} brands…`);

  const map = {};
  const misses = [];
  for (const { domain, name } of brands) {
    try {
      const file = await resolveLogoFile(name, domain);
      if (!file) {
        misses.push(`${name} (${domain})`);
        console.error(`  MISS  ${name} (${domain})`);
      } else {
        const url = await finalThumbUrl(file);
        if (!url) {
          misses.push(`${name} (${domain}) [file ${file}]`);
          console.error(`  MISS  ${name} -> ${file} (no thumb)`);
        } else {
          map[domain] = url;
          console.error(`  OK    ${name} -> ${file}`);
        }
      }
    } catch (e) {
      misses.push(`${name} (${domain}) [${e.message}]`);
      console.error(`  ERR   ${name}: ${e.message}`);
    }
    await sleep(120); // be polite to the APIs
  }

  const body =
    `// AUTO-GENERATED by scripts/resolve-logos.mjs — do not edit by hand.\n` +
    `// Official brand logos from Wikimedia (Wikidata P154). Domains not listed\n` +
    `// here fall back to the favicon proxy in lib/brands.ts.\n\n` +
    `export const WIKIMEDIA_LOGOS: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`;
  await writeFile(new URL("../lib/brand-logos.ts", import.meta.url), body);

  console.error(`\nDone. ${Object.keys(map).length} resolved, ${misses.length} misses.`);
  if (misses.length) console.error("Misses:\n" + misses.map((m) => "  - " + m).join("\n"));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
